"""changed content

Revision ID: 880274962223
Revises: ec965644a919
Create Date: 2020-08-29 13:14:07.245948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880274962223'
down_revision = 'ec965644a919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('content', sa.String(length=120000), nullable=False))
    op.drop_column('blog_post', 'contents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('contents', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('blog_post', 'content')
    # ### end Alembic commands ###
