"""added products images

Revision ID: c0895b620367
Revises: 1484059dbf06
Create Date: 2020-08-29 17:22:19.960511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0895b620367'
down_revision = '1484059dbf06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('angle1', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('angle2', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('angle3', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('mainImage', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'mainImage')
    op.drop_column('products', 'angle3')
    op.drop_column('products', 'angle2')
    op.drop_column('products', 'angle1')
    # ### end Alembic commands ###
