"""changed content to text

Revision ID: ec965644a919
Revises: 8766c8da5127
Create Date: 2020-08-29 13:10:10.039790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec965644a919'
down_revision = '8766c8da5127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('contents', sa.Text(), nullable=False))
    op.drop_column('blog_post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('content', sa.VARCHAR(length=12000), autoincrement=False, nullable=False))
    op.drop_column('blog_post', 'contents')
    # ### end Alembic commands ###
